--- #YAML:1.0
name: CGI-Application-Plugin-ValidateRM
version: 2.00
author:
  - Mark Stosberg <mark@summersault.com>
abstract: |-
  Help validate CGI::Application run modes using Data::FormValidator
license: perl
requires:
  CGI::Application: 3
  Data::FormValidator: 3.7
  HTML::FillInForm: 0
provides:
  CGI::Application::Plugin::ValidateRM:
    file: lib/CGI/Application/Plugin/ValidateRM.pm
    version: 2.00
generated_by: Module::Build version 0.2611
