--- #YAML:1.0
name: CGI-Application-Plugin-ValidateRM
version: 1.22
license: perl
distribution_type: module
requires:
  CGI::Application: 3
  Data::FormValidator: 3
  HTML::FillInForm: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  CGI::Application::Plugin::ValidateRM:
    file: lib/CGI/Application/Plugin/ValidateRM.pm
    version: 1.22
generated_by: Module::Build version 0.21
